---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sshd-conf
data:
  rsa_private: |
{{ .Files.Get  .Values.sshService.rsa_private_file | indent 4 }}
  rsa_public: {{ .Files.Get  .Values.sshService.rsa_public_file | quote }}
  authorized_keys: |
{{ .Files.Get  .Values.sshService.authorized_keys_file | indent 4 }}