---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sshd-conf
data:
  rsa_private: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAQEAw6PfzthS0WywKKBbqNOc/fOSTEucDzB94HCEQiwYWLQAcMoadJWX
    WC4ssiXdM56BjEzdb8xOmNtcAVPGyKTpPbz3cOUAyKzCncLcj4FmxkaeNGrIWXPBNwvgNo
    7VD0aCKGMcn1ON8nmH0fLxdfXOS3zVN1ilWiQUBYKLM+GjsuBh4uK13juseZZB9zTe5B72
    jNXQOMdh46/LpPGXBP0Xy+wYF9DAHDqjOFC1Ybsaftn/r3y6swDtO1zy4TpWgxTNBtjXX+
    hTg100VyhM63APLo0+3UdJ1qgLUJEfX2lCu/tc4XJNfdfKycoPPalAvgQ9YUxeOHuCZM+H
    8lkmdCqc0wAAA9iXdVN/l3VTfwAAAAdzc2gtcnNhAAABAQDDo9/O2FLRbLAooFuo05z985
    JMS5wPMH3gcIRCLBhYtABwyhp0lZdYLiyyJd0znoGMTN1vzE6Y21wBU8bIpOk9vPdw5QDI
    rMKdwtyPgWbGRp40ashZc8E3C+A2jtUPRoIoYxyfU43yeYfR8vF19c5LfNU3WKVaJBQFgo
    sz4aOy4GHi4rXeO6x5lkH3NN7kHvaM1dA4x2Hjr8uk8ZcE/RfL7BgX0MAcOqM4ULVhuxp+
    2f+vfLqzAO07XPLhOlaDFM0G2Ndf6FODXTRXKEzrcA8ujT7dR0nWqAtQkR9faUK7+1zhck
    1918rJyg89qUC+BD1hTF44e4Jkz4fyWSZ0KpzTAAAAAwEAAQAAAQA4VuPn1EIdTzh3qp5a
    wv3t4AvcbtW1Rhip3p0n1Tz5pnSOBpWRx1Z7LWjvsJm/+MCD38rRHDvyJxGazD5tn5gPkH
    CNkVUldSLifbA4n2IybTm4DJw/rmcQ7BmYfI98w6hN6yTd+Rjin/7uBhFlD/FlqcBZHO0Z
    RVSCtbJSsYMLyrMn0/pj3qrDF6sCk2DnnxWeAhG9KWkWtudvuCtSIIVTyKEgnWI6MvUNjg
    32F1wOWVIRaelHBEqozKV7TbOEicEq6bC3/drtXOtFrUnvjW9ODycVjeP6TSIu7Cfhbkt6
    MlPbgN2G/r6yBvXMdPfW4uEbaIE/Bt2Fagh630MbOnT5AAAAgQCW6Rm6ysRY4Mi5GF4mN7
    SizaFV9U6Tz9oqmhHJdC59YZ5OM61NRWj1842Ec5KGiph0T+CTo0DyDprNyRprtWoB5XkS
    nVgDZcgpO2RQ9hjrkYbtJpEAvZUvddtmSLlqAWOMXE1kskLAPMZSFuNieLsHPsJXel02xd
    bTgchV0r6N+gAAAIEA7UdGRiZfhexK+W5QPLpqEyC+O4V0jJap0CF9FXYaYtagjzUao1QB
    9HJTgwvrzMZcHXIHWxx8Bb5VbgawiHJNjJM7bXfI+XqWhwCGnYS0VWBv30cNCxoeIGputf
    WfwYb7kkXbBpS/49fBTr8pFhLWsJhjl39/iqU8btJzuxaclOcAAACBANMTjw8Z9OImcX4j
    Q4JzEBCQKfpA7vEiGxmhp5o6SW/l33t3ljYSXJWJaMFCwtYBcwNXN6xgcaWzNv2JT/8Aog
    /zM/8ecJ3oRyng0U0hNgKnDogz1QHQ/gWXxMCqLLqsKib0x8Fs9lkeo3Ew+FDQR74ntz5y
    qkabkTpKbIVHv881AAAAG3NlbWlrQHNlbWlrLmRvbWEudG9tYXNlay5jegECAwQFBgc=
    -----END OPENSSH PRIVATE KEY-----
  rsa_public: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDo9/O2FLRbLAooFuo05z985JMS5wPMH3gcIRCLBhYtABwyhp0lZdYLiyyJd0znoGMTN1vzE6Y21wBU8bIpOk9vPdw5QDIrMKdwtyPgWbGRp40ashZc8E3C+A2jtUPRoIoYxyfU43yeYfR8vF19c5LfNU3WKVaJBQFgosz4aOy4GHi4rXeO6x5lkH3NN7kHvaM1dA4x2Hjr8uk8ZcE/RfL7BgX0MAcOqM4ULVhuxp+2f+vfLqzAO07XPLhOlaDFM0G2Ndf6FODXTRXKEzrcA8ujT7dR0nWqAtQkR9faUK7+1zhck1918rJyg89qUC+BD1hTF44e4Jkz4fyWSZ0KpzT"
  authorized_keys: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEEigT76j7Ku8S5dhFRRFLD9tPO4x8VzyIOazMREi7Bq semik@domaNS"
