apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh-and-nginx.fullname" . }}-ssh
  labels:
    {{- include "ssh-and-nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sshService.type }}
  ports:
    - port: {{ .Values.sshService.port }}
      nodePort: {{ .Values.sshService.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "ssh-and-nginx.selectorLabels" . | nindent 4 }}
